async (page) => {
  const results=[];
  const check=(name,value)=>{if(!value)throw Error(name);results.push(name);};
  await page.goto('http://127.0.0.1:8766/output/playwright/fixture.html');
  await page.waitForFunction(()=>document.querySelector('video').readyState>=2);
  await page.mouse.move(5,5);
  await page.evaluate(async()=>{const v=document.querySelector('video');v.currentTime=15;await smartVideoViewer.open(smartVideoViewer.inventory()[0].id,'hide-test');});
  check('top title and exit removed', await page.evaluate(()=>{const r=document.querySelector('[data-smart-video-viewer]').shadowRoot;return !r.querySelector('.top')&&!r.querySelector('#close');}));
  const box=await page.locator('.dock').boundingBox();
  const videoBox=await page.locator('video').boundingBox();
  await page.waitForFunction(()=>document.querySelector('[data-smart-video-viewer]').shadowRoot.querySelector('.dock').hasAttribute('data-hidden'));
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('[data-smart-video-viewer]').shadowRoot.querySelector('.panel')).opacity==='0');
  check('initial controls automatically hide',true);
  await page.keyboard.press('ArrowRight');
  await page.keyboard.press('ArrowLeft');
  await page.keyboard.press('l');
  check('hidden shortcuts still seek without revealing controls',await page.evaluate(()=>{const r=document.querySelector('[data-smart-video-viewer]').shadowRoot;return document.querySelector('video').currentTime>=19.9&&r.querySelector('.dock').hasAttribute('data-hidden');}));
  await page.mouse.move(200,150);
  check('moving over video does not reveal controls',await page.locator('.dock').getAttribute('data-hidden')!==null);
  check('video geometry stays unchanged while hidden',JSON.stringify(videoBox)===JSON.stringify(await page.locator('video').boundingBox()));
  await page.screenshot({path:`output/playwright/autohide-${page.context().browser().browserType().name()}-hidden.png`});
  await page.mouse.move(box.x+20,box.y+20);
  await page.waitForFunction(()=>!document.querySelector('[data-smart-video-viewer]').shadowRoot.querySelector('.panel').inert);
  check('mouse entering original dock reveals controls',await page.locator('.dock').getAttribute('data-hidden')===null);
  const rate=page.getByRole('spinbutton',{name:'播放倍速',exact:true});
  await rate.fill('1.5'); await rate.press('ArrowUp'); await rate.press('Tab');
  check('number spinner increases by 0.1x',await page.evaluate(()=>Math.abs(document.querySelector('video').playbackRate-1.6)<.001));
  await rate.focus(); await rate.press('ArrowDown'); await rate.press('Tab');
  check('number spinner decreases by 0.1x',await page.evaluate(()=>Math.abs(document.querySelector('video').playbackRate-1.5)<.001));
  const slider=page.getByRole('slider',{name:'连续倍速滑块',exact:true});
  await slider.focus(); await slider.press('ArrowRight');
  check('slider increases by 0.1x',await page.evaluate(()=>Math.abs(document.querySelector('video').playbackRate-1.6)<.001));
  await page.waitForTimeout(2200);
  check('controls remain visible while hovered',await page.locator('.dock').getAttribute('data-hidden')===null);
  await page.getByRole('spinbutton',{name:'每次跳转秒数',exact:true}).fill('7');
  await page.getByRole('spinbutton',{name:'每次跳转秒数',exact:true}).press('Tab');
  await page.getByRole('spinbutton',{name:'播放倍速',exact:true}).focus();
  await page.mouse.move(5,5);
  await page.waitForFunction(()=>document.querySelector('[data-smart-video-viewer]').shadowRoot.querySelector('.panel').inert);
  await page.keyboard.press('ArrowLeft');
  check('hidden input focus cleared and seek setting preserved',await page.evaluate(()=>Math.abs(document.querySelector('video').currentTime-13)<.1));
  await page.keyboard.press('Tab');
  check('Tab does not reveal hidden controls',await page.locator('.dock').getAttribute('data-hidden')!==null);
  await page.mouse.move(box.x+20,box.y+20);
  await page.waitForFunction(()=>!document.querySelector('[data-smart-video-viewer]').shadowRoot.querySelector('.panel').inert);
  await page.screenshot({path:`output/playwright/autohide-${page.context().browser().browserType().name()}-visible.png`});
  await page.keyboard.press('Escape');
  check('Escape still restores original page',await page.locator('[data-smart-video-viewer]').count()===0&&await page.evaluate(()=>document.querySelector('video').controls));
  return {passed:results.length,results};
}
