async (page) => {
  const results=[];
  const check=(name,value)=>{if(!value)throw Error(name);results.push(name);};
  await page.setViewportSize({width:1280,height:1000});
  await page.goto('http://127.0.0.1:8766/output/playwright/fixture.html');
  await page.waitForFunction(()=>document.querySelector('video').readyState>=2);
  const open=async()=>{await page.evaluate(()=>smartVideoViewer.open(smartVideoViewer.inventory()[0].id,'center-test'));};
  const centered=()=>page.evaluate(()=>{const v=document.querySelector('video'),r=v.getBoundingClientRect();return Math.abs((r.top+r.bottom)/2-innerHeight/2)<1&&Math.abs((r.left+r.right)/2-innerWidth/2)<1&&Math.abs(r.width/r.height-v.videoWidth/v.videoHeight)<.001;});
  await open();
  check('picture centered both ways with intrinsic ratio',await centered());
  const rect=await page.locator('video').boundingBox();
  check('top and bottom spaces equal',Math.abs(rect.y-(1000-rect.y-rect.height))<1&&rect.y>50);
  await page.mouse.click(640,500);
  await page.waitForFunction(()=>!document.querySelector('video').paused&&document.querySelector('video').currentTime>.1);
  check('picture click plays video',true);
  await page.evaluate(()=>{window.bubbledClicks=0;document.body.addEventListener('click',()=>window.bubbledClicks++);});
  await page.mouse.click(100,50);
  check('upper empty space exits without pausing',await page.evaluate(()=>!smartVideoViewer.active()&&!document.querySelector('video').paused));
  check('exit click does not reach underlying page handlers',await page.evaluate(()=>bubbledClicks===0));
  await open();
  await page.mouse.click(20,950);
  check('lower empty space exits without pausing',await page.evaluate(()=>!smartVideoViewer.active()&&!document.querySelector('video').paused));
  await open();
  await page.mouse.click(640,500);
  check('picture click pauses without exiting',await page.evaluate(()=>smartVideoViewer.active()&&document.querySelector('video').paused));
  await page.mouse.move(5,5);
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('[data-smart-video-viewer]').shadowRoot.querySelector('.panel')).opacity==='0');
  check('hiding controls preserves centered picture',await centered());
  await page.screenshot({path:`output/playwright/centered-${page.context().browser().browserType().name()}.png`});
  await page.locator('.dock').hover();
  await page.getByText('快捷键与播放说明',{exact:true}).click();
  check('expanding controls does not move picture',await centered());
  await page.setViewportSize({width:1600,height:600});
  await page.waitForFunction(()=>{const r=document.querySelector('video').getBoundingClientRect();return Math.abs((r.left+r.right)/2-innerWidth/2)<1&&r.left>100;});
  check('wide viewport recenters picture with side spaces',await centered());
  await page.mouse.click(20,100);
  check('side empty space exits without changing paused state',await page.evaluate(()=>!smartVideoViewer.active()&&document.querySelector('video').paused));
  await page.setViewportSize({width:1280,height:720});
  return {passed:results.length,results};
}
